application: test
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: public/img
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
- url: /.*
  script: main.py
